import type { Metadata } from "next";
import "../../css/globals.css";
import Background from "@/components/Background";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Background/>
      {children}
    </>
  );
}
